#!/usr/local/bin/bash
# Case 0 - getting sources
#	env) echo "set variables to bash_profile"
    echo "set variables to bash_profile"
	a=`grep "\<CVSROOT\>" ~/.bash_profile`

		if [ "$a" = "" ]; then
			echo "CVSROOT=ldap-host.apple.com:/cvsroot" >> ~/.bash_profile
			echo "export CVSROOT">> ~/.bash_profile
			source ~/.bash_profile
			echo "CVSROOT included into ~/.bash_profile"
		else
		    echo "CVSROOT allready in ~/.bash_profile"
		fi
